name: malaria_hero
channels:
     - conda-forge
dependencies:     
     - python=3.7
     - pip
     - pandas=1.0.3
     - dash=1.4.1
     - pillow=7.0
     - scikit-learn=0.20.0
     - flask-wtf=0.14.2
     - werkzeug=0.16.1
     - gunicorn=19.9.0
     - eventlet
     - pip:
        - tensorflow==2.0.1
