channels:
     - conda-forge
dependencies:     
     - python=3.7
     - pip
     - pandas
     - scipy
     - dash
     - pillow=8.0.1
     - gunicorn
     - eventlet
     - pip:
        - tensorflow==2.0.1
