channels:
     - conda-forge
dependencies:     
     - python=3.7
     - pip
     - ipykernel
     - pandas=1.2.0
     - scipy=1.5.2
     - dash=1.18.1
     - pillow=8.0.1
     - gunicorn
     - eventlet
     - pip:
        - tensorflow==2.0.1
        - werkzeug==2.0.0
        - protobuf==3.20.1 
        - flask==2.0.3
        - jinja2==3.0.1
